[package]
name = "pocket-clear"
version = "0.1.0"
edition = "2024"
license= "GPL-2.0-only"
description = "Adds a cross-platform clear() function to easily clear the terminal"
repository = "https://github.com/AlexRedEye/pocket-clear"
readme = "README.md"

[dependencies]
